<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Example extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Example');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $example = $this->Example->get_all();

        $data = array(
            'example_data' => $example
        );

        $this->template->load('template','example/groups_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Example->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'name' => $row->name,
		'description' => $row->description,
	    );
            $this->load->view('example/groups_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('example'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('example/create_action'),
	    'id' => set_value('id'),
	    'name' => set_value('name'),
	    'description' => set_value('description'),
	);
        $this->template->load('template','example/groups_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
		'description' => $this->input->post('description',TRUE),
	    );

            $this->Example->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('example'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Example->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('example/update_action'),
		'id' => set_value('id', $row->id),
		'name' => set_value('name', $row->name),
		'description' => set_value('description', $row->description),
	    );
            $this->template->load('template','example/groups_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('example'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
		'description' => $this->input->post('description',TRUE),
	    );

            $this->Example->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('example'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Example->get_by_id($id);

        if ($row) {
            $this->Example->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('example'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('example'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('name', 'name', 'trim|required');
	$this->form_validation->set_rules('description', 'description', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Example.php */
/* Location: ./application/controllers/Example.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-20 17:41:44 */
/* http://harviacode.com */